### ISSUE TITLE
Use conda for installation

### ISSUE THREAD

**Issue by ruestefa** [MeteoSwiss-APN/pyflexplot#9]
* PyFlexPlot version: v0.15.5

### Description

So far, pyflexplot has been using the standard venv module to create virtual environments during installation. This requires some workarounds for packages depending on system libraries, namely cartopy (and its dependency shapely) depending on geos and proj. To build against the installed geos and proj versions, cartopy and shapely are installed from github (and cartopy has additionally been forked to add a pyproject.toml to enable seamless installation with pip).

### Solution

The dependencies problems can be solved by switching from "pip+venv" to conda (specifically, miniconda), which handles not only python dependencies, but also their non-python dependencies.

Potential drawback: The resulting virtual environments are substantially larger and may reach multiple GBs each. However, conda should be smart enough to share identical installations between environments with hardlinks, so this should not matter.

### Tasks

- [x] Make conda available on tsa (ask Dani)
- [x] Figure out how to use conda with pyflexplot (for both development and deployment)
- [x] Adapt makefile for conda
- [x] Merge adapted makefile into blueprint (in parallel or as an alternative to "venv+pip"-makefile)

**Comment by ruestefa** [comment]
# Conda on tsa

- Dani has installed miniconda on his /scratch for testing
  - Problem: I cannot create envs because I don't have write permissions there!
- Research [conda for multiple users](https://docs.anaconda.com/anaconda/install/multi-user/)
  - Multiuser installation requires root and a designated group; not sure that's the way to go for OSM
- For testing, I'll just use my conda installation on /project/s1063 (like on daint)

## Outlook

- For deployment, a standard single-user OSM installation is sufficient
- Other users best just install their own miniconda if they want to use conda
- Maybe a central standard environment could eventually be provided by OSM to cover standard use cases (like at IAC)

**Comment by ruestefa** [comment]
# Install miniconda

- On daint (/project), I've installed it with easybuild, which is not available on tsa (AFAIK)
- Follow [installation instructions](https://conda.io/projects/conda/en/latest/user-guide/install/linux.html)

```bash
wget https://repo.anaconda.com/miniconda/Miniconda3-py39_4.9.2-Linux-x86_64.sh
sha256sum Miniconda3-py39_4.9.2-Linux-x86_64.sh | grep -q '^536817d1b14cb1ada88900f5be51ce0a5e042bae178b5550e62f61e223deae7c' && echo OK
bash Miniconda3-py39_4.9.2-Linux-x86_64.sh
```

```
Welcome to Miniconda3 py39_4.9.2

In order to continue the installation process, please review the license
agreement.
Please, press ENTER to continue
>>>
...
Do you accept the license terms? [yes|no]
[no] >>> yes  

Miniconda3 will now be installed into this location:
/users/ruestefa/miniconda3

  - Press ENTER to confirm the location
  - Press CTRL-C to abort the installation
  - Or specify a different location below

[/users/ruestefa/miniconda3] >>> /scratch/ruestefa/miniconda3
PREFIX=/scratch/ruestefa/miniconda3
Unpacking payload ...
Collecting package metadata (current_repodata.json): done                                                                                          
Solving environment: done
...
Preparing transaction: done
Executing transaction: done
installation finished.
Do you wish the installer to initialize Miniconda3
by running conda init? [yes|no]
[no] >>> no

You have chosen to not have conda modify your shell scripts at all.
To activate conda's base environment in your current shell session:

eval "$(/scratch/ruestefa/miniconda3/bin/conda shell.YOUR_SHELL_NAME hook)" 

To install conda's shell functions for easier access, first activate, then:

conda init

If you'd prefer that conda's base environment not be activated on startup, 
   set the auto_activate_base parameter to false: 

conda config --set auto_activate_base false

Thank you for installing Miniconda3!
```

- The code to initialize conda was not appended to ~/.bashrc because I answered "no"
  - Users who always want to activate it and don't care too much about their bashrc should just answer "yes"
- Function that initializes conda with command `conda-init` (put in ~/.bashrc):

  ```bash
    # Show hint how to initialize conda
    undef conda
    function conda { echo "Initialize conda: conda-init" >&2; }

    # Command to initialize conda
    function conda-init()
    {
        local conda_path="/scratch/ruestefa/miniconda3"
        local conda_name="conda"

        # Unset temporary function defined above
        undef conda
        echo "initializing ${conda_name} from ${conda_path}" >&2

        # Based on the block of code created by 'conda init':
        #
        # # >>> conda initialize >>>
        # # !! Contents within this block are managed by 'conda init' !!
        # __conda_setup="$('/scratch/ruestefa/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
        # if [ $? -eq 0 ]; then
        #     eval "$__conda_setup"
        # else
        #     if [ -f "/scratch/ruestefa/miniconda3/etc/profile.d/conda.sh" ]; then
        #         . "/scratch/ruestefa/miniconda3/etc/profile.d/conda.sh"
        #     else
        #         export PATH="/scratch/ruestefa/miniconda3/bin:$PATH"
        #     fi
        # fi
        # unset __conda_setup
        # # <<< conda initialize <<<

        local __conda_setup="$("${conda_path}/bin/conda" 'shell.bash' 'hook' 2> /dev/null)"
        if [ ${?} -eq 0 ]; then
            eval "${__conda_setup}"
        else
            if [ -f "${conda_path}/etc/profile.d/conda.sh" ]; then
                . "${conda_path}/etc/profile.d/conda.sh"
            else
                export PATH="${conda_path}bin:$PATH"
            fi
        fi
    }
  ```

  - Masks `conda` command to prompt user to initialize it with `conda-init`
  - When `conda-init` is run, the `conda` command is unmasked and conda is initialized
  - The code inserted by conda in ~/.bashrc if one answers "yes" is shown as a comment
- In new shell:

  ```
  $ conda-init
  initializing conda from /scratch/ruestefa/miniconda3
  $ which conda
  /scratch/ruestefa/miniconda3/condabin/conda
  $ conda -V
  conda 4.9.2
  $ conda
  usage: conda [-h] [-V] command ...

  conda is a tool for managing and deploying applications, environments and packages.

  Options:

  positional arguments:
    command
      clean        Remove unused packages and caches.
      compare      Compare packages between conda environments.
      config       Modify configuration values in .condarc. This is modeled after the git config command. Writes to the user .condarc file
                   (/users/ruestefa/.condarc) by default.
      create       Create a new conda environment from a list of specified packages.
      help         Displays a list of available conda commands and their help strings.
      info         Display information about current conda install.
      init         Initialize conda for shell interaction. [Experimental]
      install      Installs a list of packages into a specified conda environment.
      list         List linked packages in a conda environment.
      package      Low-level conda package utility. (EXPERIMENTAL)
      remove       Remove a list of packages from a specified conda environment.
      uninstall    Alias for conda remove.
      run          Run an executable in a conda environment. [Experimental]
      search       Search for packages and display associated information. The input is a MatchSpec, a query language for conda packages. See
                   examples below.
      update       Updates conda packages to the latest compatible version.
      upgrade      Alias for conda update.

  optional arguments:
    -h, --help     Show this help message and exit.
    -V, --version  Show the conda version number and exit.

  conda commands available from other packages:
    env
  ```

  - Works! :-)
